### ISSUE TITLE
feat: Copy option

### ISSUE THREAD

**Issue by sandy1709** [orca-group/pulsar#10]
It Will great if you add copy option along with the Home, GitHub and Docs option.
If i want to copy text from server it will be easy by just clicking that button.

**Comment by lukewhrit** [comment]
Sorry about the almost year it took to respond to this issue due to work and burnout but I would be happy to include this feature in the upcoming rewrite of the software I have planned!

**Comment by lukewhrit** [comment]
We should also include a button to direct users to the Plain Text edition of the document alongside the Copy button.
